version: '3'

services:
	
	mariadb:
		container_name: mariadb
		restart: unless-stopped
		expose:
			- "3306"
		networks:
			- inception
		build:
			context: requirements/mariadb
			dockerfile: Dockerfile
		env_files: .env
		volumes:
			- mariadb:/var/lib/mysql

	wordpress:
		container_name: wordpress
		build:
			context: requirements/wordpress
			dockerfile: Dockerfile
		env_files: .env
		volumes:
			- wordpress:/var/www/wordpress:nocopy
		networks:
			- inception
		depends_on:
			- mariadb
		restart: on-failure
		expose:
			- "9000"
		
	nginx:
		container_name: nginx
		restart: on-failure
		build:
			context: requirements/nginx
			dockerfile: Dockerfile
		volumes:
			- wordpress:/var/www/wordpress
		networks:
			-inception
		env_file: .env
		ports:
			- "443:443"
		
		
